/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tercerreto_odph;

import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.regex.*;
import java.util.*;
import javax.swing.JOptionPane;
import tercerreto_odph.Classes.Cliente;

/**
 *
 * @author odpinerosh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    ArrayList<Cliente> LISTA_CLIENTES = new ArrayList<>(); 
    
    public MainFrame() {
        
        initComponents();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tabGroup = new javax.swing.JTabbedPane();
        tabCliente = new javax.swing.JPanel();
        txtDocumento = new javax.swing.JTextField();
        lblDocumento = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        panBotonesCliente = new javax.swing.JPanel();
        btnNuevoCliente = new javax.swing.JButton();
        btnGrabarCliente = new javax.swing.JButton();
        btnLimpiarTabCliente = new javax.swing.JButton();
        btnSalirTabCliente = new javax.swing.JButton();
        tabCtaAhorros = new javax.swing.JPanel();
        panBotonesAhorro = new javax.swing.JPanel();
        btnNvaCtaAhorro = new javax.swing.JButton();
        btnCalcIntAhorro = new javax.swing.JButton();
        btnGrabCtaAhorro = new javax.swing.JButton();
        btnLimpiarTabAhorro = new javax.swing.JButton();
        btnSalirTabAhorro = new javax.swing.JButton();
        lblNumAhorros = new javax.swing.JLabel();
        lblFechAhorros = new javax.swing.JLabel();
        lblIntAhorros = new javax.swing.JLabel();
        lblSaldoAhorros = new javax.swing.JLabel();
        txtNumAhorros = new javax.swing.JTextField();
        calFechAhorros = new com.toedter.calendar.JDateChooser();
        spinIntAhorros = new javax.swing.JSpinner();
        txtSaldoAhorros = new javax.swing.JFormattedTextField();
        lblSaldoAhorros1 = new javax.swing.JLabel();
        txtRendAhorros = new javax.swing.JFormattedTextField();
        tabCtaCorriente = new javax.swing.JPanel();
        panBotonesCorriente = new javax.swing.JPanel();
        btnNvaCtaAhorro1 = new javax.swing.JButton();
        btnCalcIntAhorro1 = new javax.swing.JButton();
        btnGrabCtaAhorro1 = new javax.swing.JButton();
        btnLimpiarTabAhorro1 = new javax.swing.JButton();
        btnSalirTabAhorro1 = new javax.swing.JButton();
        lblNumCorriente = new javax.swing.JLabel();
        spinIntCorriente = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        lblIntCorriente = new javax.swing.JLabel();
        lblSaldoCorriente = new javax.swing.JLabel();
        txtNumCorriente = new javax.swing.JTextField();
        calFechCorriente = new com.toedter.calendar.JDateChooser();
        lblSobreCorriente = new javax.swing.JLabel();
        lblRendCorriente = new javax.swing.JLabel();
        txtSaldoCorriente = new javax.swing.JFormattedTextField();
        txtSobreCorriente = new javax.swing.JFormattedTextField();
        txtRendCorriente = new javax.swing.JFormattedTextField();
        tabCDAT = new javax.swing.JPanel();
        spinPlazoCDT = new javax.swing.JSpinner();
        txtMontoCDT = new javax.swing.JFormattedTextField();
        lblFechCDT = new javax.swing.JLabel();
        lblPlazoCDT = new javax.swing.JLabel();
        panBotonesCDT = new javax.swing.JPanel();
        btnNvaCtaAhorro2 = new javax.swing.JButton();
        btnCalcIntAhorro2 = new javax.swing.JButton();
        btnGrabCtaAhorro2 = new javax.swing.JButton();
        btnLimpiarTabAhorro2 = new javax.swing.JButton();
        btnSalirTabAhorro2 = new javax.swing.JButton();
        lblSaldoCorriente1 = new javax.swing.JLabel();
        txtNumCDT = new javax.swing.JTextField();
        txtRendCDT = new javax.swing.JFormattedTextField();
        calFechCDT = new com.toedter.calendar.JDateChooser();
        lblRendCorriente1 = new javax.swing.JLabel();
        lblNumCDT = new javax.swing.JLabel();
        lblIntCDT = new javax.swing.JLabel();
        spinIntCDT = new javax.swing.JSpinner();
        lblRendCorriente2 = new javax.swing.JLabel();
        txtRetCDT = new javax.swing.JFormattedTextField();
        tabTCredito = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco");

        tabGroup.setBackground(new java.awt.Color(255, 255, 255));
        tabGroup.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabCliente.setBackground(new java.awt.Color(255, 255, 255));
        tabCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtDocumento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDocumento.setEnabled(false);
        txtDocumento.setName(""); // NOI18N

        lblDocumento.setText("Documento:");

        lblNombre.setText("Nombre:");

        lblCorreo.setText("Correo Electrónico:");

        lblCelular.setText("Núm. Celular:");

        lblDireccion.setText("Dirección:");

        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombre.setEnabled(false);

        txtCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCorreo.setEnabled(false);

        txtCelular.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCelular.setEnabled(false);

        txtDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDireccion.setEnabled(false);
        txtDireccion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtDireccionActionPerformed(evt);
            }
        });

        btnNuevoCliente.setMnemonic('N');
        btnNuevoCliente.setText("Nuevo");
        btnNuevoCliente.setToolTipText("");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnGrabarCliente.setMnemonic('G');
        btnGrabarCliente.setText("Grabar");
        btnGrabarCliente.setEnabled(false);
        btnGrabarCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGrabarClienteActionPerformed(evt);
            }
        });

        btnLimpiarTabCliente.setMnemonic('L');
        btnLimpiarTabCliente.setText("Limpiar");
        btnLimpiarTabCliente.setEnabled(false);
        btnLimpiarTabCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLimpiarTabClienteActionPerformed(evt);
            }
        });

        btnSalirTabCliente.setMnemonic('S');
        btnSalirTabCliente.setText("Salir");
        btnSalirTabCliente.setToolTipText("");
        btnSalirTabCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirTabClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonesClienteLayout = new javax.swing.GroupLayout(panBotonesCliente);
        panBotonesCliente.setLayout(panBotonesClienteLayout);
        panBotonesClienteLayout.setHorizontalGroup(
            panBotonesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrabarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarTabCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(btnSalirTabCliente)
                .addGap(46, 46, 46))
        );
        panBotonesClienteLayout.setVerticalGroup(
            panBotonesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBotonesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCliente)
                    .addComponent(btnGrabarCliente)
                    .addComponent(btnLimpiarTabCliente)
                    .addComponent(btnSalirTabCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabClienteLayout = new javax.swing.GroupLayout(tabCliente);
        tabCliente.setLayout(tabClienteLayout);
        tabClienteLayout.setHorizontalGroup(
            tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panBotonesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabClienteLayout.createSequentialGroup()
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabClienteLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblDocumento)
                                    .addComponent(lblDireccion)))
                            .addComponent(lblCorreo)
                            .addGroup(tabClienteLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblCelular)))
                        .addGap(18, 18, 18)
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        tabClienteLayout.setVerticalGroup(
            tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabClienteLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumento)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(panBotonesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tabGroup.addTab("Cliente", tabCliente);
        tabCliente.getAccessibleContext().setAccessibleName("tbdCliente");

        tabCtaAhorros.setBackground(new java.awt.Color(255, 255, 255));
        tabCtaAhorros.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNvaCtaAhorro.setMnemonic('N');
        btnNvaCtaAhorro.setText("Nuevo");
        btnNvaCtaAhorro.setToolTipText("");
        btnNvaCtaAhorro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNvaCtaAhorroActionPerformed(evt);
            }
        });

        btnCalcIntAhorro.setMnemonic('C');
        btnCalcIntAhorro.setText("Calcular");
        btnCalcIntAhorro.setToolTipText("");
        btnCalcIntAhorro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCalcIntAhorroActionPerformed(evt);
            }
        });

        btnGrabCtaAhorro.setMnemonic('G');
        btnGrabCtaAhorro.setText("Grabar");

        btnLimpiarTabAhorro.setMnemonic('L');
        btnLimpiarTabAhorro.setText("Limpiar");
        btnLimpiarTabAhorro.setToolTipText("");

        btnSalirTabAhorro.setMnemonic('S');
        btnSalirTabAhorro.setText("Salir");
        btnSalirTabAhorro.setToolTipText("");
        btnSalirTabAhorro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirTabAhorroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonesAhorroLayout = new javax.swing.GroupLayout(panBotonesAhorro);
        panBotonesAhorro.setLayout(panBotonesAhorroLayout);
        panBotonesAhorroLayout.setHorizontalGroup(
            panBotonesAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesAhorroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnNvaCtaAhorro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcIntAhorro)
                .addGap(18, 18, 18)
                .addComponent(btnGrabCtaAhorro)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarTabAhorro)
                .addGap(18, 18, 18)
                .addComponent(btnSalirTabAhorro)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panBotonesAhorroLayout.setVerticalGroup(
            panBotonesAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBotonesAhorroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panBotonesAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNvaCtaAhorro)
                    .addComponent(btnCalcIntAhorro)
                    .addComponent(btnGrabCtaAhorro)
                    .addComponent(btnLimpiarTabAhorro)
                    .addComponent(btnSalirTabAhorro))
                .addContainerGap())
        );

        lblNumAhorros.setText("Cuenta número:");

        lblFechAhorros.setText("Fecha de apertura:");

        lblIntAhorros.setText("Interés pactado:");

        lblSaldoAhorros.setText("Saldo:");

        spinIntAhorros.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 4.0d, 0.1d));

        txtSaldoAhorros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtSaldoAhorros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblSaldoAhorros1.setText("Interés generado:");

        txtRendAhorros.setEditable(false);
        txtRendAhorros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtRendAhorros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout tabCtaAhorrosLayout = new javax.swing.GroupLayout(tabCtaAhorros);
        tabCtaAhorros.setLayout(tabCtaAhorrosLayout);
        tabCtaAhorrosLayout.setHorizontalGroup(
            tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCtaAhorrosLayout.createSequentialGroup()
                .addGroup(tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCtaAhorrosLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panBotonesAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabCtaAhorrosLayout.createSequentialGroup()
                                .addGroup(tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIntAhorros)
                                    .addComponent(lblNumAhorros)
                                    .addGroup(tabCtaAhorrosLayout.createSequentialGroup()
                                        .addComponent(lblSaldoAhorros)
                                        .addGap(10, 10, 10)))
                                .addGap(18, 18, 18)
                                .addGroup(tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabCtaAhorrosLayout.createSequentialGroup()
                                        .addComponent(spinIntAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblFechAhorros)
                                        .addGap(18, 18, 18)
                                        .addComponent(calFechAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNumAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSaldoAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(tabCtaAhorrosLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblSaldoAhorros1)
                        .addGap(28, 28, 28)
                        .addComponent(txtRendAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        tabCtaAhorrosLayout.setVerticalGroup(
            tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCtaAhorrosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumAhorros))
                .addGap(18, 18, 18)
                .addGroup(tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIntAhorros)
                        .addComponent(spinIntAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechAhorros))
                    .addComponent(calFechAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoAhorros)
                    .addComponent(txtSaldoAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCtaAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoAhorros1)
                    .addComponent(txtRendAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(panBotonesAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        tabGroup.addTab("Cta. Ahorros", tabCtaAhorros);

        tabCtaCorriente.setBackground(new java.awt.Color(255, 255, 255));
        tabCtaCorriente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNvaCtaAhorro1.setMnemonic('N');
        btnNvaCtaAhorro1.setText("Nuevo");
        btnNvaCtaAhorro1.setToolTipText("");
        btnNvaCtaAhorro1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNvaCtaAhorro1ActionPerformed(evt);
            }
        });

        btnCalcIntAhorro1.setMnemonic('C');
        btnCalcIntAhorro1.setText("Calcular");
        btnCalcIntAhorro1.setToolTipText("");
        btnCalcIntAhorro1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCalcIntAhorro1ActionPerformed(evt);
            }
        });

        btnGrabCtaAhorro1.setMnemonic('G');
        btnGrabCtaAhorro1.setText("Grabar");

        btnLimpiarTabAhorro1.setMnemonic('L');
        btnLimpiarTabAhorro1.setText("Limpiar");
        btnLimpiarTabAhorro1.setToolTipText("");

        btnSalirTabAhorro1.setMnemonic('S');
        btnSalirTabAhorro1.setText("Salir");
        btnSalirTabAhorro1.setToolTipText("");
        btnSalirTabAhorro1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirTabAhorro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonesCorrienteLayout = new javax.swing.GroupLayout(panBotonesCorriente);
        panBotonesCorriente.setLayout(panBotonesCorrienteLayout);
        panBotonesCorrienteLayout.setHorizontalGroup(
            panBotonesCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesCorrienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnNvaCtaAhorro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcIntAhorro1)
                .addGap(18, 18, 18)
                .addComponent(btnGrabCtaAhorro1)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarTabAhorro1)
                .addGap(18, 18, 18)
                .addComponent(btnSalirTabAhorro1)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panBotonesCorrienteLayout.setVerticalGroup(
            panBotonesCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBotonesCorrienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panBotonesCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNvaCtaAhorro1)
                    .addComponent(btnCalcIntAhorro1)
                    .addComponent(btnGrabCtaAhorro1)
                    .addComponent(btnLimpiarTabAhorro1)
                    .addComponent(btnSalirTabAhorro1))
                .addContainerGap())
        );

        lblNumCorriente.setText("Cuenta número:");

        spinIntCorriente.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 4.0d, 0.1d));

        jLabel5.setText("Fecha de apertura:");

        lblIntCorriente.setText("Interés pactado:");

        lblSaldoCorriente.setText("Saldo:");

        lblSobreCorriente.setText("Sobregiro:");

        lblRendCorriente.setText("Interés generado:");

        txtSaldoCorriente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtSaldoCorriente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtSobreCorriente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtSobreCorriente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtRendCorriente.setEditable(false);
        txtRendCorriente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtRendCorriente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout tabCtaCorrienteLayout = new javax.swing.GroupLayout(tabCtaCorriente);
        tabCtaCorriente.setLayout(tabCtaCorrienteLayout);
        tabCtaCorrienteLayout.setHorizontalGroup(
            tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCtaCorrienteLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCtaCorrienteLayout.createSequentialGroup()
                        .addGroup(tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSaldoCorriente)
                            .addComponent(lblNumCorriente)
                            .addComponent(lblSobreCorriente)
                            .addComponent(lblRendCorriente)
                            .addComponent(lblIntCorriente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabCtaCorrienteLayout.createSequentialGroup()
                                .addGroup(tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSaldoCorriente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabCtaCorrienteLayout.createSequentialGroup()
                                        .addComponent(spinIntCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel5))
                                    .addComponent(txtRendCorriente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSobreCorriente, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calFechCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(panBotonesCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        tabCtaCorrienteLayout.setVerticalGroup(
            tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCtaCorrienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumCorriente))
                .addGap(18, 18, 18)
                .addGroup(tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIntCorriente)
                        .addComponent(spinIntCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(calFechCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoCorriente)
                    .addComponent(txtSaldoCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSobreCorriente)
                    .addComponent(txtSobreCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCtaCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRendCorriente)
                    .addComponent(txtRendCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(panBotonesCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        tabGroup.addTab("Cta. Corriente", tabCtaCorriente);

        tabCDAT.setBackground(new java.awt.Color(255, 255, 255));
        tabCDAT.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        spinPlazoCDT.setModel(new javax.swing.SpinnerNumberModel(1, 1, 60, 1));

        txtMontoCDT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtMontoCDT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblFechCDT.setText("Fecha de apertura:");

        lblPlazoCDT.setText("Plazo:");

        btnNvaCtaAhorro2.setMnemonic('N');
        btnNvaCtaAhorro2.setText("Nuevo");
        btnNvaCtaAhorro2.setToolTipText("");
        btnNvaCtaAhorro2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNvaCtaAhorro2ActionPerformed(evt);
            }
        });

        btnCalcIntAhorro2.setMnemonic('C');
        btnCalcIntAhorro2.setText("Calcular");
        btnCalcIntAhorro2.setToolTipText("");
        btnCalcIntAhorro2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCalcIntAhorro2ActionPerformed(evt);
            }
        });

        btnGrabCtaAhorro2.setMnemonic('G');
        btnGrabCtaAhorro2.setText("Grabar");

        btnLimpiarTabAhorro2.setMnemonic('L');
        btnLimpiarTabAhorro2.setText("Limpiar");
        btnLimpiarTabAhorro2.setToolTipText("");

        btnSalirTabAhorro2.setMnemonic('S');
        btnSalirTabAhorro2.setText("Salir");
        btnSalirTabAhorro2.setToolTipText("");
        btnSalirTabAhorro2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirTabAhorro2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonesCDTLayout = new javax.swing.GroupLayout(panBotonesCDT);
        panBotonesCDT.setLayout(panBotonesCDTLayout);
        panBotonesCDTLayout.setHorizontalGroup(
            panBotonesCDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesCDTLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnNvaCtaAhorro2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcIntAhorro2)
                .addGap(18, 18, 18)
                .addComponent(btnGrabCtaAhorro2)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarTabAhorro2)
                .addGap(18, 18, 18)
                .addComponent(btnSalirTabAhorro2)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panBotonesCDTLayout.setVerticalGroup(
            panBotonesCDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBotonesCDTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panBotonesCDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNvaCtaAhorro2)
                    .addComponent(btnCalcIntAhorro2)
                    .addComponent(btnGrabCtaAhorro2)
                    .addComponent(btnLimpiarTabAhorro2)
                    .addComponent(btnSalirTabAhorro2))
                .addContainerGap())
        );

        lblSaldoCorriente1.setText("Monto:");

        txtRendCDT.setEditable(false);
        txtRendCDT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtRendCDT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblRendCorriente1.setText("Interés generado:");

        lblNumCDT.setText("Número del CDT:");

        lblIntCDT.setText("Interés pactado:");

        spinIntCDT.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 12.0d, 0.1d));

        lblRendCorriente2.setText("Valor retorno:");

        txtRetCDT.setEditable(false);
        txtRetCDT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtRetCDT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout tabCDATLayout = new javax.swing.GroupLayout(tabCDAT);
        tabCDAT.setLayout(tabCDATLayout);
        tabCDATLayout.setHorizontalGroup(
            tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCDATLayout.createSequentialGroup()
                .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCDATLayout.createSequentialGroup()
                        .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabCDATLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNumCDT)
                                    .addComponent(lblSaldoCorriente1)
                                    .addComponent(lblPlazoCDT)))
                            .addGroup(tabCDATLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRendCorriente2)
                                    .addComponent(lblRendCorriente1))))
                        .addGap(18, 18, 18)
                        .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtRendCDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(txtMontoCDT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRetCDT)))
                    .addGroup(tabCDATLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(spinPlazoCDT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(lblIntCDT)
                        .addGap(18, 18, 18)
                        .addComponent(spinIntCDT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabCDATLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(txtNumCDT, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFechCDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calFechCDT, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabCDATLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(panBotonesCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        tabCDATLayout.setVerticalGroup(
            tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCDATLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechCDT)
                        .addComponent(lblNumCDT))
                    .addComponent(calFechCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinPlazoCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntCDT)
                    .addComponent(spinIntCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlazoCDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldoCorriente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRendCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRendCorriente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCDATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRetCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRendCorriente2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(panBotonesCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        tabGroup.addTab("CDAT", tabCDAT);

        tabTCredito.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout tabTCreditoLayout = new javax.swing.GroupLayout(tabTCredito);
        tabTCredito.setLayout(tabTCreditoLayout);
        tabTCreditoLayout.setHorizontalGroup(
            tabTCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        tabTCreditoLayout.setVerticalGroup(
            tabTCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        tabGroup.addTab("Tj. Crédito", tabTCredito);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tabGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(tabGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtDireccionActionPerformed
    {//GEN-HEADEREND:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNuevoClienteActionPerformed
    {//GEN-HEADEREND:event_btnNuevoClienteActionPerformed
        // Recorrer los componentes de la pestaña y activarlos si son
        // de tipo JTextField
        for (Component comp : tabCliente.getComponents()) {
            if (comp instanceof javax.swing.JTextField) {
                ((javax.swing.JTextField)comp).setEnabled(true);
                ((javax.swing.JTextField)comp).setText("");
            }
        }
        
        //Pone el foco en el Documento del cliente
        txtDocumento.requestFocus();
        btnNuevoCliente.setEnabled(false);
        btnGrabarCliente.setEnabled(true);
        btnLimpiarTabCliente.setEnabled(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnSalirTabClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirTabClienteActionPerformed
    {//GEN-HEADEREND:event_btnSalirTabClienteActionPerformed
        // TODO add your handling code here:
      System.exit(0);
    }//GEN-LAST:event_btnSalirTabClienteActionPerformed

    private void btnGrabarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGrabarClienteActionPerformed
    {//GEN-HEADEREND:event_btnGrabarClienteActionPerformed
        // TODO add your handling code here:
        String nomCliente, docCliente, mailCliente, celCliente, dirCliente;
      
        Cliente objCliente = new Cliente();
        
        if (funValidaString(docCliente = txtDocumento.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "El documento del Cliente no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtDocumento.requestFocus();
            return;
        } else {
            objCliente.setDocCliente(docCliente);
        }

        if (funValidaString(nomCliente = txtNombre.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "El nombre del Cliente no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
            return;
        } else {
            objCliente.setNomCliente(nomCliente);
        }        

        //objCliente.setDirCliente(txtDireccion.getText());
        if (funValidaString(dirCliente = txtDireccion.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "La dirección del Cliente no puede ser nula.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtDireccion.requestFocus();
            return;
        } else {
            objCliente.setDirCliente(dirCliente);
        }        
       
        //objCliente.setEmailCliente(txtCorreo.getText());
        if (funValidaString(mailCliente = txtCorreo.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "El correo del Cliente no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtCorreo.requestFocus();
            return;
        } else {
            //Validar el formato del correo electrónico con RegEx.
            Pattern pat = Pattern.compile("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$");
            Matcher mat = pat.matcher(mailCliente);                                                                           
            if (!mat.matches()) {
                JOptionPane.showMessageDialog(rootPane, "El formato del correo no es correcto.","¡Atención!", JOptionPane.ERROR_MESSAGE);                                                                       
                txtCorreo.requestFocus();
                txtCorreo.selectAll();
                return;
            } else {
                objCliente.setEmailCliente(mailCliente);
            }
        }
        
        //objCliente.setCelCliente(txtCelular.getText());
        if (funValidaString(celCliente = txtCelular.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "El celular del Cliente no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtCelular.requestFocus();
            return;
        } else {
            objCliente.setCelCliente(celCliente);
        }
        
        LISTA_CLIENTES.add(objCliente);
        JOptionPane.showMessageDialog(rootPane, "Se grabó el cliente. Hay " + LISTA_CLIENTES.size() + " clientes registrados.", "Cliente guardado", JOptionPane.INFORMATION_MESSAGE);
        
        for (Component comp : tabCliente.getComponents()) {
            if (comp instanceof javax.swing.JTextField) {
                ((javax.swing.JTextField)comp).setEnabled(false);
            } else {
                if (comp instanceof javax.swing.JPanel) {
                    for (Component panComp : panBotonesCliente.getComponents()) {
                        if (((javax.swing.JButton)panComp).getText() == "Nuevo" || ((javax.swing.JButton)panComp).getText() == "Salir") {
                            ((javax.swing.JButton)panComp).setEnabled(true);
                        } else {
                            ((javax.swing.JButton)panComp).setEnabled(false);
                        }
                    }
                }
            }
        }
        
        
        
    }//GEN-LAST:event_btnGrabarClienteActionPerformed

    private void btnLimpiarTabClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLimpiarTabClienteActionPerformed
    {//GEN-HEADEREND:event_btnLimpiarTabClienteActionPerformed
        // TODO add your handling code here:
        // Recorrer los componentes de la pestaña y vaciarlos si son
        // de tipo JTextField
        for (Component comp : tabCliente.getComponents()) {
            if (comp instanceof javax.swing.JTextField) {
                ((javax.swing.JTextField)comp).setText("");
            }
        }
        //Pone el foco en el Documento del cliente
        txtDocumento.requestFocus();
    }//GEN-LAST:event_btnLimpiarTabClienteActionPerformed

    private void btnNvaCtaAhorroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNvaCtaAhorroActionPerformed
    {//GEN-HEADEREND:event_btnNvaCtaAhorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNvaCtaAhorroActionPerformed

    private void btnCalcIntAhorroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCalcIntAhorroActionPerformed
    {//GEN-HEADEREND:event_btnCalcIntAhorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcIntAhorroActionPerformed

    private void btnSalirTabAhorroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirTabAhorroActionPerformed
    {//GEN-HEADEREND:event_btnSalirTabAhorroActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirTabAhorroActionPerformed

    private void btnNvaCtaAhorro1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNvaCtaAhorro1ActionPerformed
    {//GEN-HEADEREND:event_btnNvaCtaAhorro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNvaCtaAhorro1ActionPerformed

    private void btnCalcIntAhorro1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCalcIntAhorro1ActionPerformed
    {//GEN-HEADEREND:event_btnCalcIntAhorro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcIntAhorro1ActionPerformed

    private void btnSalirTabAhorro1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirTabAhorro1ActionPerformed
    {//GEN-HEADEREND:event_btnSalirTabAhorro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirTabAhorro1ActionPerformed

    private void btnNvaCtaAhorro2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNvaCtaAhorro2ActionPerformed
    {//GEN-HEADEREND:event_btnNvaCtaAhorro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNvaCtaAhorro2ActionPerformed

    private void btnCalcIntAhorro2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCalcIntAhorro2ActionPerformed
    {//GEN-HEADEREND:event_btnCalcIntAhorro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcIntAhorro2ActionPerformed

    private void btnSalirTabAhorro2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirTabAhorro2ActionPerformed
    {//GEN-HEADEREND:event_btnSalirTabAhorro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirTabAhorro2ActionPerformed

    private int funValidaString(String aux) {
        
        if (aux.length() > 0) {
            return 0;
        } else {
            return 1;
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcIntAhorro;
    private javax.swing.JButton btnCalcIntAhorro1;
    private javax.swing.JButton btnCalcIntAhorro2;
    private javax.swing.JButton btnGrabCtaAhorro;
    private javax.swing.JButton btnGrabCtaAhorro1;
    private javax.swing.JButton btnGrabCtaAhorro2;
    private javax.swing.JButton btnGrabarCliente;
    private javax.swing.JButton btnLimpiarTabAhorro;
    private javax.swing.JButton btnLimpiarTabAhorro1;
    private javax.swing.JButton btnLimpiarTabAhorro2;
    private javax.swing.JButton btnLimpiarTabCliente;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNvaCtaAhorro;
    private javax.swing.JButton btnNvaCtaAhorro1;
    private javax.swing.JButton btnNvaCtaAhorro2;
    private javax.swing.JButton btnSalirTabAhorro;
    private javax.swing.JButton btnSalirTabAhorro1;
    private javax.swing.JButton btnSalirTabAhorro2;
    private javax.swing.JButton btnSalirTabCliente;
    private com.toedter.calendar.JDateChooser calFechAhorros;
    private com.toedter.calendar.JDateChooser calFechCDT;
    private com.toedter.calendar.JDateChooser calFechCorriente;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblFechAhorros;
    private javax.swing.JLabel lblFechCDT;
    private javax.swing.JLabel lblIntAhorros;
    private javax.swing.JLabel lblIntCDT;
    private javax.swing.JLabel lblIntCorriente;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumAhorros;
    private javax.swing.JLabel lblNumCDT;
    private javax.swing.JLabel lblNumCorriente;
    private javax.swing.JLabel lblPlazoCDT;
    private javax.swing.JLabel lblRendCorriente;
    private javax.swing.JLabel lblRendCorriente1;
    private javax.swing.JLabel lblRendCorriente2;
    private javax.swing.JLabel lblSaldoAhorros;
    private javax.swing.JLabel lblSaldoAhorros1;
    private javax.swing.JLabel lblSaldoCorriente;
    private javax.swing.JLabel lblSaldoCorriente1;
    private javax.swing.JLabel lblSobreCorriente;
    private javax.swing.JPanel panBotonesAhorro;
    private javax.swing.JPanel panBotonesCDT;
    private javax.swing.JPanel panBotonesCliente;
    private javax.swing.JPanel panBotonesCorriente;
    private javax.swing.JSpinner spinIntAhorros;
    private javax.swing.JSpinner spinIntCDT;
    private javax.swing.JSpinner spinIntCorriente;
    private javax.swing.JSpinner spinPlazoCDT;
    private javax.swing.JPanel tabCDAT;
    private javax.swing.JPanel tabCliente;
    private javax.swing.JPanel tabCtaAhorros;
    private javax.swing.JPanel tabCtaCorriente;
    private javax.swing.JTabbedPane tabGroup;
    private javax.swing.JPanel tabTCredito;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JFormattedTextField txtMontoCDT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumAhorros;
    private javax.swing.JTextField txtNumCDT;
    private javax.swing.JTextField txtNumCorriente;
    private javax.swing.JFormattedTextField txtRendAhorros;
    private javax.swing.JFormattedTextField txtRendCDT;
    private javax.swing.JFormattedTextField txtRendCorriente;
    private javax.swing.JFormattedTextField txtRetCDT;
    private javax.swing.JFormattedTextField txtSaldoAhorros;
    private javax.swing.JFormattedTextField txtSaldoCorriente;
    private javax.swing.JFormattedTextField txtSobreCorriente;
    // End of variables declaration//GEN-END:variables
}
