/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tercerreto_odph;

import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.regex.*;
import java.util.*;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import tercerreto_odph.Classes.CDT;
import tercerreto_odph.Classes.Cliente;
import tercerreto_odph.Classes.CuentaAhorros;
import tercerreto_odph.Classes.CuentaCorriente;

/**
 *
 * @author odpinerosh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    ArrayList<Cliente> LISTA_CLIENTES = new ArrayList<>(); 
    ArrayList<CuentaAhorros> LISTA_AHORROS = new ArrayList<>();
    ArrayList<CuentaCorriente> LISTA_CORRIENTE = new ArrayList<>();
    ArrayList<CDT> LISTA_CDT = new ArrayList<>();
    
    
    public MainFrame() {
        
        initComponents();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tabGroup = new javax.swing.JTabbedPane();
        tabCliente = new javax.swing.JPanel();
        txtDocumento = new javax.swing.JTextField();
        lblDocumento = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        panBotonesCliente = new javax.swing.JPanel();
        btnNuevoCliente = new javax.swing.JButton();
        btnGrabarCliente = new javax.swing.JButton();
        btnLimpiarTabCliente = new javax.swing.JButton();
        btnSalirTabCliente = new javax.swing.JButton();
        tabCtaAhorros = new javax.swing.JPanel();
        lblNumAhorros = new javax.swing.JLabel();
        lblFechAhorros = new javax.swing.JLabel();
        lblIntAhorros = new javax.swing.JLabel();
        lblSaldoAhorros = new javax.swing.JLabel();
        txtNumAhorros = new javax.swing.JTextField();
        calFechAhorros = new com.toedter.calendar.JDateChooser();
        spinIntAhorros = new javax.swing.JSpinner();
        txtSaldoAhorros = new javax.swing.JFormattedTextField();
        lblIngGenAhorro = new javax.swing.JLabel();
        txtRendAhorros = new javax.swing.JFormattedTextField();
        panBotonesAhorro = new javax.swing.JPanel();
        btnNvaCtaAhorro = new javax.swing.JButton();
        btnCalcIntAhorro = new javax.swing.JButton();
        btnGrabCtaAhorro = new javax.swing.JButton();
        btnLimpiarTabAhorro = new javax.swing.JButton();
        btnSalirTabAhorro = new javax.swing.JButton();
        tabCtaCorriente = new javax.swing.JPanel();
        panBotonesCorriente = new javax.swing.JPanel();
        btnNvaCtaCorriente = new javax.swing.JButton();
        btnCalcIntCorriente = new javax.swing.JButton();
        btnGrabCtaCorriente = new javax.swing.JButton();
        btnLimpiarTabCorriente = new javax.swing.JButton();
        btnSalirTabCorriente = new javax.swing.JButton();
        lblNumCorriente = new javax.swing.JLabel();
        spinIntCorriente = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        lblIntCorriente = new javax.swing.JLabel();
        lblSaldoCorriente = new javax.swing.JLabel();
        txtNumCorriente = new javax.swing.JTextField();
        calFechCorriente = new com.toedter.calendar.JDateChooser();
        lblSobreCorriente = new javax.swing.JLabel();
        lblRendCorriente = new javax.swing.JLabel();
        txtSaldoCorriente = new javax.swing.JFormattedTextField();
        txtSobreCorriente = new javax.swing.JFormattedTextField();
        txtRendCorriente = new javax.swing.JFormattedTextField();
        tabCDAT = new javax.swing.JPanel();
        spinPlazoCDT = new javax.swing.JSpinner();
        txtMontoCDT = new javax.swing.JFormattedTextField();
        lblFechCDT = new javax.swing.JLabel();
        lblPlazoCDT = new javax.swing.JLabel();
        panBotonesCDT = new javax.swing.JPanel();
        btnNvoCDT = new javax.swing.JButton();
        btnCalcIntCDT = new javax.swing.JButton();
        btnGrabCDT = new javax.swing.JButton();
        btnLimpiarTabCDT = new javax.swing.JButton();
        btnSalirTabCDT = new javax.swing.JButton();
        lblMontoCDT = new javax.swing.JLabel();
        txtNumCDT = new javax.swing.JTextField();
        txtRendCDT = new javax.swing.JFormattedTextField();
        calFechCDT = new com.toedter.calendar.JDateChooser();
        lblIntGenCDT = new javax.swing.JLabel();
        lblNumCDT = new javax.swing.JLabel();
        lblIntCDT = new javax.swing.JLabel();
        spinIntCDT = new javax.swing.JSpinner();
        lblRetCDT = new javax.swing.JLabel();
        txtRetCDT = new javax.swing.JFormattedTextField();
        tabTCredito = new javax.swing.JPanel();
        spinIntPactado = new javax.swing.JSpinner();
        txtCupoTarj = new javax.swing.JFormattedTextField();
        lblIntTarj = new javax.swing.JLabel();
        panBotonesTarj = new javax.swing.JPanel();
        btnNvaTarj = new javax.swing.JButton();
        btnCalcTarj = new javax.swing.JButton();
        btnGrabTarj = new javax.swing.JButton();
        btnLimpiarTabTarj = new javax.swing.JButton();
        btnSalirTabTarj = new javax.swing.JButton();
        lblCupoAsignado = new javax.swing.JLabel();
        txtUsadoTarj = new javax.swing.JFormattedTextField();
        txtNumTarj = new javax.swing.JTextField();
        txtIntGenerado = new javax.swing.JFormattedTextField();
        lblCupoUsado = new javax.swing.JLabel();
        lblIntGenerado = new javax.swing.JLabel();
        lblNumTarj = new javax.swing.JLabel();
        calFechExp = new com.toedter.calendar.JDateChooser();
        lblFechExp = new javax.swing.JLabel();
        lblFechVenc = new javax.swing.JLabel();
        calFechVenc = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco");

        tabGroup.setBackground(new java.awt.Color(255, 255, 255));
        tabGroup.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabCliente.setBackground(new java.awt.Color(255, 255, 255));
        tabCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDocumento.setEnabled(false);
        txtDocumento.setName(""); // NOI18N
        tabCliente.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 157, 30));

        lblDocumento.setText("Documento:");
        tabCliente.add(lblDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 30));

        lblNombre.setText("Nombre:");
        tabCliente.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 30));

        lblCorreo.setText("Correo Electrónico:");
        tabCliente.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 30));

        lblCelular.setText("Núm. Celular:");
        tabCliente.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 30));

        lblDireccion.setText("Dirección:");
        tabCliente.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 30));

        txtNombre.setEnabled(false);
        tabCliente.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 361, 30));

        txtCorreo.setEnabled(false);
        tabCliente.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 198, 30));

        txtCelular.setEnabled(false);
        tabCliente.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 160, 30));

        txtDireccion.setEnabled(false);
        txtDireccion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtDireccionActionPerformed(evt);
            }
        });
        tabCliente.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 361, 30));

        btnNuevoCliente.setMnemonic('N');
        btnNuevoCliente.setText("Nuevo");
        btnNuevoCliente.setToolTipText("");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnGrabarCliente.setMnemonic('G');
        btnGrabarCliente.setText("Grabar");
        btnGrabarCliente.setEnabled(false);
        btnGrabarCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGrabarClienteActionPerformed(evt);
            }
        });

        btnLimpiarTabCliente.setMnemonic('L');
        btnLimpiarTabCliente.setText("Limpiar");
        btnLimpiarTabCliente.setEnabled(false);
        btnLimpiarTabCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLimpiarTabClienteActionPerformed(evt);
            }
        });

        btnSalirTabCliente.setMnemonic('S');
        btnSalirTabCliente.setText("Salir");
        btnSalirTabCliente.setToolTipText("");
        btnSalirTabCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirTabClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonesClienteLayout = new javax.swing.GroupLayout(panBotonesCliente);
        panBotonesCliente.setLayout(panBotonesClienteLayout);
        panBotonesClienteLayout.setHorizontalGroup(
            panBotonesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoCliente)
                .addGap(32, 32, 32)
                .addComponent(btnGrabarCliente)
                .addGap(39, 39, 39)
                .addComponent(btnLimpiarTabCliente)
                .addGap(32, 32, 32)
                .addComponent(btnSalirTabCliente)
                .addContainerGap())
        );
        panBotonesClienteLayout.setVerticalGroup(
            panBotonesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBotonesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCliente)
                    .addComponent(btnGrabarCliente)
                    .addComponent(btnLimpiarTabCliente)
                    .addComponent(btnSalirTabCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabCliente.add(panBotonesCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 251, -1, -1));

        tabGroup.addTab("Cliente", tabCliente);
        tabCliente.getAccessibleContext().setAccessibleName("tbdCliente");

        tabCtaAhorros.setBackground(new java.awt.Color(255, 255, 255));
        tabCtaAhorros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabCtaAhorros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumAhorros.setText("Cuenta número:");
        tabCtaAhorros.add(lblNumAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        lblFechAhorros.setText("Fecha de apertura:");
        tabCtaAhorros.add(lblFechAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        lblIntAhorros.setText("Interés pactado:");
        tabCtaAhorros.add(lblIntAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        lblSaldoAhorros.setText("Saldo:");
        tabCtaAhorros.add(lblSaldoAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        txtNumAhorros.setEnabled(false);
        tabCtaAhorros.add(txtNumAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 36, 218, 30));

        calFechAhorros.setEnabled(false);
        tabCtaAhorros.add(calFechAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 134, 30));

        spinIntAhorros.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 4.0d, 0.1d));
        spinIntAhorros.setEnabled(false);
        tabCtaAhorros.add(spinIntAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 66, 30));

        txtSaldoAhorros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtSaldoAhorros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSaldoAhorros.setEnabled(false);
        tabCtaAhorros.add(txtSaldoAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 211, 30));

        lblIngGenAhorro.setText("Interés generado:");
        tabCtaAhorros.add(lblIngGenAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtRendAhorros.setEditable(false);
        txtRendAhorros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtRendAhorros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRendAhorros.setEnabled(false);
        tabCtaAhorros.add(txtRendAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 211, 30));

        btnNvaCtaAhorro.setMnemonic('N');
        btnNvaCtaAhorro.setText("Nuevo");
        btnNvaCtaAhorro.setToolTipText("");
        btnNvaCtaAhorro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNvaCtaAhorroActionPerformed(evt);
            }
        });

        btnCalcIntAhorro.setMnemonic('C');
        btnCalcIntAhorro.setText("Calcular");
        btnCalcIntAhorro.setToolTipText("");
        btnCalcIntAhorro.setEnabled(false);
        btnCalcIntAhorro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCalcIntAhorroActionPerformed(evt);
            }
        });

        btnGrabCtaAhorro.setMnemonic('G');
        btnGrabCtaAhorro.setText("Grabar");
        btnGrabCtaAhorro.setEnabled(false);
        btnGrabCtaAhorro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGrabCtaAhorroActionPerformed(evt);
            }
        });

        btnLimpiarTabAhorro.setMnemonic('L');
        btnLimpiarTabAhorro.setText("Limpiar");
        btnLimpiarTabAhorro.setToolTipText("");
        btnLimpiarTabAhorro.setEnabled(false);
        btnLimpiarTabAhorro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLimpiarTabAhorroActionPerformed(evt);
            }
        });

        btnSalirTabAhorro.setMnemonic('S');
        btnSalirTabAhorro.setText("Salir");
        btnSalirTabAhorro.setToolTipText("");
        btnSalirTabAhorro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirTabAhorroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonesAhorroLayout = new javax.swing.GroupLayout(panBotonesAhorro);
        panBotonesAhorro.setLayout(panBotonesAhorroLayout);
        panBotonesAhorroLayout.setHorizontalGroup(
            panBotonesAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesAhorroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnNvaCtaAhorro)
                .addGap(18, 18, 18)
                .addComponent(btnCalcIntAhorro)
                .addGap(18, 18, 18)
                .addComponent(btnGrabCtaAhorro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarTabAhorro)
                .addGap(18, 18, 18)
                .addComponent(btnSalirTabAhorro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panBotonesAhorroLayout.setVerticalGroup(
            panBotonesAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBotonesAhorroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panBotonesAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNvaCtaAhorro)
                    .addComponent(btnGrabCtaAhorro)
                    .addComponent(btnLimpiarTabAhorro)
                    .addComponent(btnSalirTabAhorro)
                    .addComponent(btnCalcIntAhorro))
                .addContainerGap())
        );

        tabCtaAhorros.add(panBotonesAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 40));

        tabGroup.addTab("Cta. Ahorros", tabCtaAhorros);

        tabCtaCorriente.setBackground(new java.awt.Color(255, 255, 255));
        tabCtaCorriente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabCtaCorriente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNvaCtaCorriente.setMnemonic('N');
        btnNvaCtaCorriente.setText("Nuevo");
        btnNvaCtaCorriente.setToolTipText("");
        btnNvaCtaCorriente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNvaCtaCorrienteActionPerformed(evt);
            }
        });

        btnCalcIntCorriente.setMnemonic('C');
        btnCalcIntCorriente.setText("Calcular");
        btnCalcIntCorriente.setToolTipText("");
        btnCalcIntCorriente.setEnabled(false);
        btnCalcIntCorriente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCalcIntCorrienteActionPerformed(evt);
            }
        });

        btnGrabCtaCorriente.setMnemonic('G');
        btnGrabCtaCorriente.setText("Grabar");
        btnGrabCtaCorriente.setEnabled(false);
        btnGrabCtaCorriente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGrabCtaCorrienteActionPerformed(evt);
            }
        });

        btnLimpiarTabCorriente.setMnemonic('L');
        btnLimpiarTabCorriente.setText("Limpiar");
        btnLimpiarTabCorriente.setToolTipText("");
        btnLimpiarTabCorriente.setEnabled(false);
        btnLimpiarTabCorriente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLimpiarTabCorrienteActionPerformed(evt);
            }
        });

        btnSalirTabCorriente.setMnemonic('S');
        btnSalirTabCorriente.setText("Salir");
        btnSalirTabCorriente.setToolTipText("");
        btnSalirTabCorriente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirTabCorrienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonesCorrienteLayout = new javax.swing.GroupLayout(panBotonesCorriente);
        panBotonesCorriente.setLayout(panBotonesCorrienteLayout);
        panBotonesCorrienteLayout.setHorizontalGroup(
            panBotonesCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesCorrienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnNvaCtaCorriente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcIntCorriente)
                .addGap(18, 18, 18)
                .addComponent(btnGrabCtaCorriente)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarTabCorriente)
                .addGap(18, 18, 18)
                .addComponent(btnSalirTabCorriente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panBotonesCorrienteLayout.setVerticalGroup(
            panBotonesCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBotonesCorrienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panBotonesCorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNvaCtaCorriente)
                    .addComponent(btnCalcIntCorriente)
                    .addComponent(btnGrabCtaCorriente)
                    .addComponent(btnLimpiarTabCorriente)
                    .addComponent(btnSalirTabCorriente))
                .addContainerGap())
        );

        tabCtaCorriente.add(panBotonesCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        lblNumCorriente.setText("Cuenta número:");
        tabCtaCorriente.add(lblNumCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        spinIntCorriente.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.1d, 4.0d, 0.1d));
        spinIntCorriente.setEnabled(false);
        tabCtaCorriente.add(spinIntCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 76, 66, 30));

        jLabel5.setText("Fecha de apertura:");
        tabCtaCorriente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        lblIntCorriente.setText("Interés pactado:");
        tabCtaCorriente.add(lblIntCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        lblSaldoCorriente.setText("Saldo:");
        tabCtaCorriente.add(lblSaldoCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        txtNumCorriente.setEnabled(false);
        tabCtaCorriente.add(txtNumCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 218, 30));

        calFechCorriente.setEnabled(false);
        tabCtaCorriente.add(calFechCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 76, 134, 30));

        lblSobreCorriente.setText("Sobregiro:");
        tabCtaCorriente.add(lblSobreCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        lblRendCorriente.setText("Interés generado:");
        tabCtaCorriente.add(lblRendCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        txtSaldoCorriente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtSaldoCorriente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSaldoCorriente.setEnabled(false);
        tabCtaCorriente.add(txtSaldoCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 215, 30));

        txtSobreCorriente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtSobreCorriente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSobreCorriente.setText("0");
        txtSobreCorriente.setEnabled(false);
        tabCtaCorriente.add(txtSobreCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 215, 30));

        txtRendCorriente.setEditable(false);
        txtRendCorriente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtRendCorriente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRendCorriente.setEnabled(false);
        tabCtaCorriente.add(txtRendCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 215, 30));

        tabGroup.addTab("Cta. Corriente", tabCtaCorriente);

        tabCDAT.setBackground(new java.awt.Color(255, 255, 255));
        tabCDAT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabCDAT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spinPlazoCDT.setModel(new javax.swing.SpinnerNumberModel(1, 1, 60, 1));
        spinPlazoCDT.setEnabled(false);
        tabCDAT.add(spinPlazoCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 66, 30));

        txtMontoCDT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtMontoCDT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMontoCDT.setEnabled(false);
        tabCDAT.add(txtMontoCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 215, 30));

        lblFechCDT.setText("Fecha de apertura:");
        tabCDAT.add(lblFechCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        lblPlazoCDT.setText("Plazo:");
        tabCDAT.add(lblPlazoCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        btnNvoCDT.setMnemonic('N');
        btnNvoCDT.setText("Nuevo");
        btnNvoCDT.setToolTipText("");
        btnNvoCDT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNvoCDTActionPerformed(evt);
            }
        });

        btnCalcIntCDT.setMnemonic('C');
        btnCalcIntCDT.setText("Calcular");
        btnCalcIntCDT.setToolTipText("");
        btnCalcIntCDT.setEnabled(false);
        btnCalcIntCDT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCalcIntCDTActionPerformed(evt);
            }
        });

        btnGrabCDT.setMnemonic('G');
        btnGrabCDT.setText("Grabar");
        btnGrabCDT.setEnabled(false);
        btnGrabCDT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGrabCDTActionPerformed(evt);
            }
        });

        btnLimpiarTabCDT.setMnemonic('L');
        btnLimpiarTabCDT.setText("Limpiar");
        btnLimpiarTabCDT.setToolTipText("");
        btnLimpiarTabCDT.setEnabled(false);
        btnLimpiarTabCDT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLimpiarTabCDTActionPerformed(evt);
            }
        });

        btnSalirTabCDT.setMnemonic('S');
        btnSalirTabCDT.setText("Salir");
        btnSalirTabCDT.setToolTipText("");
        btnSalirTabCDT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirTabCDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonesCDTLayout = new javax.swing.GroupLayout(panBotonesCDT);
        panBotonesCDT.setLayout(panBotonesCDTLayout);
        panBotonesCDTLayout.setHorizontalGroup(
            panBotonesCDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesCDTLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnNvoCDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcIntCDT)
                .addGap(18, 18, 18)
                .addComponent(btnGrabCDT)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarTabCDT)
                .addGap(18, 18, 18)
                .addComponent(btnSalirTabCDT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panBotonesCDTLayout.setVerticalGroup(
            panBotonesCDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBotonesCDTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panBotonesCDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNvoCDT)
                    .addComponent(btnCalcIntCDT)
                    .addComponent(btnGrabCDT)
                    .addComponent(btnLimpiarTabCDT)
                    .addComponent(btnSalirTabCDT))
                .addContainerGap())
        );

        tabCDAT.add(panBotonesCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        lblMontoCDT.setText("Monto:");
        tabCDAT.add(lblMontoCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        txtNumCDT.setEnabled(false);
        tabCDAT.add(txtNumCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 115, 30));

        txtRendCDT.setEditable(false);
        txtRendCDT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtRendCDT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRendCDT.setEnabled(false);
        tabCDAT.add(txtRendCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 215, 30));

        calFechCDT.setEnabled(false);
        tabCDAT.add(calFechCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 134, 30));

        lblIntGenCDT.setText("Interés generado:");
        tabCDAT.add(lblIntGenCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lblNumCDT.setText("Número del CDT:");
        tabCDAT.add(lblNumCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        lblIntCDT.setText("Interés pactado:");
        tabCDAT.add(lblIntCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        spinIntCDT.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 12.0d, 0.1d));
        spinIntCDT.setEnabled(false);
        tabCDAT.add(spinIntCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 66, 30));

        lblRetCDT.setText("Valor retorno:");
        tabCDAT.add(lblRetCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        txtRetCDT.setEditable(false);
        txtRetCDT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtRetCDT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRetCDT.setEnabled(false);
        tabCDAT.add(txtRetCDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 215, 30));

        tabGroup.addTab("CDAT", tabCDAT);

        tabTCredito.setBackground(new java.awt.Color(255, 255, 255));
        tabTCredito.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabTCredito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spinIntPactado.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 4.0d, 0.1d));
        spinIntPactado.setEnabled(false);
        tabTCredito.add(spinIntPactado, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 20, 66, 30));

        txtCupoTarj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtCupoTarj.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCupoTarj.setEnabled(false);
        txtCupoTarj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtCupoTarjActionPerformed(evt);
            }
        });
        tabTCredito.add(txtCupoTarj, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 113, 200, 30));

        lblIntTarj.setText("Tasa interés:");
        tabTCredito.add(lblIntTarj, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 25, -1, -1));

        btnNvaTarj.setMnemonic('N');
        btnNvaTarj.setText("Nuevo");
        btnNvaTarj.setToolTipText("");
        btnNvaTarj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNvaTarjActionPerformed(evt);
            }
        });

        btnCalcTarj.setMnemonic('C');
        btnCalcTarj.setText("Calcular");
        btnCalcTarj.setToolTipText("");
        btnCalcTarj.setEnabled(false);
        btnCalcTarj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCalcTarjActionPerformed(evt);
            }
        });

        btnGrabTarj.setMnemonic('G');
        btnGrabTarj.setText("Grabar");
        btnGrabTarj.setEnabled(false);

        btnLimpiarTabTarj.setMnemonic('L');
        btnLimpiarTabTarj.setText("Limpiar");
        btnLimpiarTabTarj.setToolTipText("");
        btnLimpiarTabTarj.setEnabled(false);

        btnSalirTabTarj.setMnemonic('S');
        btnSalirTabTarj.setText("Salir");
        btnSalirTabTarj.setToolTipText("");
        btnSalirTabTarj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirTabTarjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonesTarjLayout = new javax.swing.GroupLayout(panBotonesTarj);
        panBotonesTarj.setLayout(panBotonesTarjLayout);
        panBotonesTarjLayout.setHorizontalGroup(
            panBotonesTarjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesTarjLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnNvaTarj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcTarj)
                .addGap(18, 18, 18)
                .addComponent(btnGrabTarj)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarTabTarj)
                .addGap(18, 18, 18)
                .addComponent(btnSalirTabTarj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panBotonesTarjLayout.setVerticalGroup(
            panBotonesTarjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonesTarjLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBotonesTarjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNvaTarj)
                    .addComponent(btnCalcTarj)
                    .addComponent(btnGrabTarj)
                    .addComponent(btnLimpiarTabTarj)
                    .addComponent(btnSalirTabTarj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabTCredito.add(panBotonesTarj, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        lblCupoAsignado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCupoAsignado.setText("Cupo asignado:");
        tabTCredito.add(lblCupoAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 113, -1, 26));

        txtUsadoTarj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtUsadoTarj.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUsadoTarj.setEnabled(false);
        tabTCredito.add(txtUsadoTarj, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 157, 200, 30));

        txtNumTarj.setEnabled(false);
        tabTCredito.add(txtNumTarj, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 218, 30));

        txtIntGenerado.setEditable(false);
        txtIntGenerado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtIntGenerado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tabTCredito.add(txtIntGenerado, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 201, 200, 30));

        lblCupoUsado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCupoUsado.setText("Cupo utilizado:");
        tabTCredito.add(lblCupoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 157, 98, 26));

        lblIntGenerado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIntGenerado.setText("Interés generado:");
        tabTCredito.add(lblIntGenerado, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 201, -1, 26));

        lblNumTarj.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumTarj.setText("Tarjeta #:");
        tabTCredito.add(lblNumTarj, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 25, -1, -1));

        calFechExp.setEnabled(false);
        tabTCredito.add(calFechExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 134, 30));

        lblFechExp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechExp.setText("Expedición:");
        tabTCredito.add(lblFechExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 58, 96, 26));

        lblFechVenc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechVenc.setText("Vencimiento:");
        tabTCredito.add(lblFechVenc, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 58, -1, 26));

        calFechVenc.setEnabled(false);
        tabTCredito.add(calFechVenc, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 58, 134, 30));

        tabGroup.addTab("Tj. Crédito", tabTCredito);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tabGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tabGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirTabTarjActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirTabTarjActionPerformed
    {//GEN-HEADEREND:event_btnSalirTabTarjActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirTabTarjActionPerformed

    private void btnCalcTarjActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCalcTarjActionPerformed
    {//GEN-HEADEREND:event_btnCalcTarjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcTarjActionPerformed

    private void btnNvaTarjActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNvaTarjActionPerformed
    {//GEN-HEADEREND:event_btnNvaTarjActionPerformed
        // TODO add your handling code here:
        txtNumTarj.setEnabled(true);
        txtNumTarj.requestFocus();
        spinIntPactado.setEnabled(true);
        calFechExp.setEnabled(true);
        calFechVenc.setEnabled(true);
        txtCupoTarj.setEnabled(true);
        txtUsadoTarj.setEnabled(true);
        
        btnNvaTarj.setEnabled(false);
        btnCalcTarj.setEnabled(true);
        btnGrabTarj.setEnabled(true);
        btnLimpiarTabTarj.setEnabled(true);
        
    }//GEN-LAST:event_btnNvaTarjActionPerformed

    private void txtCupoTarjActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtCupoTarjActionPerformed
    {//GEN-HEADEREND:event_txtCupoTarjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCupoTarjActionPerformed

    private void btnSalirTabCDTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirTabCDTActionPerformed
    {//GEN-HEADEREND:event_btnSalirTabCDTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirTabCDTActionPerformed

    private void btnCalcIntCDTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCalcIntCDTActionPerformed
    {//GEN-HEADEREND:event_btnCalcIntCDTActionPerformed
        // TODO add your handling code here:
        Double interesGeneradoCDT, valorRetornoCDT; 
        
        if(funValidaString(txtNumCDT.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "El número del CDT es requerido","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtNumCDT.requestFocus();
            return;
        }
        
        if(calFechCDT.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "Se requiere la fecha de apertura del CDT","¡Atención!", JOptionPane.ERROR_MESSAGE);
            calFechCDT.requestFocus();
            return;
        }
        
        if(txtMontoCDT.getValue() == null || ((Number)txtMontoCDT.getValue()).intValue() <= 0) {
            JOptionPane.showMessageDialog(rootPane, "El monto del CDT debe ser diferente de cero","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtMontoCDT.requestFocus();
            return;
        }
        
        interesGeneradoCDT = ((Number)spinIntCDT.getValue()).doubleValue() * ((Number)txtMontoCDT.getValue()).doubleValue() / 100;
        valorRetornoCDT = ((Number)spinPlazoCDT.getValue()).doubleValue() * interesGeneradoCDT;
        
        txtRendCDT.setValue(interesGeneradoCDT);
        txtRetCDT.setValue(valorRetornoCDT);
        
    }//GEN-LAST:event_btnCalcIntCDTActionPerformed

    private void btnNvoCDTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNvoCDTActionPerformed
    {//GEN-HEADEREND:event_btnNvoCDTActionPerformed
        // TODO add your handling code here:
        txtNumCDT.setEnabled(true);
        txtNumCDT.requestFocus();
        calFechCDT.setEnabled(true);
        spinPlazoCDT.setEnabled(true);
        spinIntCDT.setEnabled(true);
        txtMontoCDT.setEnabled(true);
        txtRendCDT.setEnabled(true);
        txtRetCDT.setEnabled(true);
        
        btnNvoCDT.setEnabled(false);
        btnCalcIntCDT.setEnabled(true);
        btnGrabCDT.setEnabled(true);
        btnLimpiarTabCDT.setEnabled(true);
        
        txtNumCDT.setText("");
        calFechCDT.setDate(null);
        spinPlazoCDT.setValue(1);
        spinIntCDT.setValue(1);
        txtMontoCDT.setValue(null);
        txtRendCDT.setValue(null);
        txtRetCDT.setValue(null);
    }//GEN-LAST:event_btnNvoCDTActionPerformed

    private void btnSalirTabCorrienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirTabCorrienteActionPerformed
    {//GEN-HEADEREND:event_btnSalirTabCorrienteActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirTabCorrienteActionPerformed

    private void btnCalcIntCorrienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCalcIntCorrienteActionPerformed
    {//GEN-HEADEREND:event_btnCalcIntCorrienteActionPerformed
        // TODO add your handling code here:
        double rendCorriente = 0;
        
        if(funValidaString(txtNumCorriente.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "Se requiere el número de la cuenta","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtNumCorriente.requestFocus();
            return;
        }
        
       if(txtSaldoCorriente.getValue() == null) {
            JOptionPane.showMessageDialog(rootPane, "El saldo de la cuenta es requerido.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtSaldoCorriente.requestFocus();
            return;
        }
       
        if(calFechCorriente.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "La fecha de apertura es requerida", "¡Atención!", JOptionPane.ERROR_MESSAGE);
            calFechCorriente.requestFocus();
        }
        
        if(txtSobreCorriente.getValue() == null) {
            txtSobreCorriente.setValue(0);
        }
        
        if( ((Number)txtSobreCorriente.getValue()).intValue() == 0 ) {
            rendCorriente = (((Number)spinIntCorriente.getValue()).doubleValue()) * ((Number)txtSaldoCorriente.getValue()).doubleValue() / 100;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cuenta en Sobregiro. Se cobrará un interés del 3%", "¡Atención!", JOptionPane.INFORMATION_MESSAGE);
            rendCorriente = ((Number)txtSobreCorriente.getValue()).doubleValue() * -3/100;
            txtRendCorriente.setForeground(Color.red);
            
        }
        
        txtRendCorriente.setValue(rendCorriente);
        
        
    }//GEN-LAST:event_btnCalcIntCorrienteActionPerformed

    private void btnNvaCtaCorrienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNvaCtaCorrienteActionPerformed
    {//GEN-HEADEREND:event_btnNvaCtaCorrienteActionPerformed
        // TODO add your handling code here:
        txtNumCorriente.setEnabled(true);
        txtNumCorriente.requestFocus();
        calFechCorriente.setEnabled(true);
        txtSaldoCorriente.setEnabled(true);
        txtSobreCorriente.setEnabled(true);
        txtRendCorriente.setEnabled(true);
        spinIntCorriente.setEnabled(true);
        
        btnNvaCtaCorriente.setEnabled(false);
        btnCalcIntCorriente.setEnabled(true);
        btnGrabCtaCorriente.setEnabled(true);
        btnLimpiarTabCorriente.setEnabled(true);
        
        txtNumCorriente.setText("");
        spinIntCorriente.setValue(1);
        calFechCorriente.setDate(null);
        txtSaldoCorriente.setValue(null);
        txtSobreCorriente.setValue(null);
        txtRendCorriente.setValue(null);
        txtRendCorriente.setForeground(Color.BLACK);
        
        
    }//GEN-LAST:event_btnNvaCtaCorrienteActionPerformed

    private void btnSalirTabAhorroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirTabAhorroActionPerformed
    {//GEN-HEADEREND:event_btnSalirTabAhorroActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirTabAhorroActionPerformed

    private void btnNvaCtaAhorroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNvaCtaAhorroActionPerformed
    {//GEN-HEADEREND:event_btnNvaCtaAhorroActionPerformed
        // TODO add your handling code here:
        txtNumAhorros.setEnabled(true);
        txtNumAhorros.requestFocus();
        calFechAhorros.setEnabled(true);
        spinIntAhorros.setEnabled(true);
        txtSaldoAhorros.setEnabled(true);
        txtRendAhorros.setEnabled(true);

        btnNvaCtaAhorro.setEnabled(false);
        btnCalcIntAhorro.setEnabled(true);
        btnGrabCtaAhorro.setEnabled(true);
        btnLimpiarTabAhorro.setEnabled(true);
        
        txtNumAhorros.setText("");
        txtSaldoAhorros.setValue(null);
        txtRendAhorros.setValue(null);
        spinIntAhorros.setValue(1);
        calFechAhorros.setDate(null);

    }//GEN-LAST:event_btnNvaCtaAhorroActionPerformed

    private void btnSalirTabClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirTabClienteActionPerformed
    {//GEN-HEADEREND:event_btnSalirTabClienteActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirTabClienteActionPerformed

    private void btnLimpiarTabClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLimpiarTabClienteActionPerformed
    {//GEN-HEADEREND:event_btnLimpiarTabClienteActionPerformed
        // TODO add your handling code here:
        // Recorrer los componentes de la pestaña y vaciarlos si son
        // de tipo JTextField
        for (Component comp : tabCliente.getComponents())
        {
            if (comp instanceof javax.swing.JTextField)
            {
                ((javax.swing.JTextField)comp).setText("");
            }
        }
        //Pone el foco en el Documento del cliente
        txtDocumento.requestFocus();
    }//GEN-LAST:event_btnLimpiarTabClienteActionPerformed

    private void btnGrabarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGrabarClienteActionPerformed
    {//GEN-HEADEREND:event_btnGrabarClienteActionPerformed
        // TODO add your handling code here:
        String nomCliente, docCliente, mailCliente, celCliente, dirCliente;

        Cliente objCliente = new Cliente();

        if (funValidaString(docCliente = txtDocumento.getText()) == 1)
        {
            JOptionPane.showMessageDialog(rootPane, "El documento del Cliente no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtDocumento.requestFocus();
            return;
        } else
        {
            objCliente.setDocCliente(docCliente);
        }

        if (funValidaString(nomCliente = txtNombre.getText()) == 1)
        {
            JOptionPane.showMessageDialog(rootPane, "El nombre del Cliente no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
            return;
            
        } else
        {
            objCliente.setNomCliente(nomCliente);
        }

        //objCliente.setDirCliente(txtDireccion.getText());
        if (funValidaString(dirCliente = txtDireccion.getText()) == 1)
        {
            JOptionPane.showMessageDialog(rootPane, "La dirección del Cliente no puede ser nula.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtDireccion.requestFocus();
            return;
        } else
        {
            objCliente.setDirCliente(dirCliente);
        }

        //objCliente.setEmailCliente(txtCorreo.getText());
        if (funValidaString(mailCliente = txtCorreo.getText()) == 1)
        {
            JOptionPane.showMessageDialog(rootPane, "El correo del Cliente no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtCorreo.requestFocus();
            return;
        } else
        {
            //Validar el formato del correo electrónico con RegEx.
            Pattern pat = Pattern.compile("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$");
            Matcher mat = pat.matcher(mailCliente);
            if (!mat.matches())
            {
                JOptionPane.showMessageDialog(rootPane, "El formato del correo no es correcto.","¡Atención!", JOptionPane.ERROR_MESSAGE);
                txtCorreo.requestFocus();
                txtCorreo.selectAll();
                return;
            } else
            {
                objCliente.setEmailCliente(mailCliente);
            }
        }

        //objCliente.setCelCliente(txtCelular.getText());
        if (funValidaString(celCliente = txtCelular.getText()) == 1)
        {
            JOptionPane.showMessageDialog(rootPane, "El celular del Cliente no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtCelular.requestFocus();
            return;
        } else
        {
            objCliente.setCelCliente(celCliente);
        }

        LISTA_CLIENTES.add(objCliente);
        JOptionPane.showMessageDialog(rootPane, "Se grabó el cliente. Hay " + LISTA_CLIENTES.size() + " clientes registrados.", "Cliente guardado", JOptionPane.INFORMATION_MESSAGE);

        for (Component comp : tabCliente.getComponents())
        {
            if (comp instanceof javax.swing.JTextField)
            {
                ((javax.swing.JTextField)comp).setEnabled(false);
            } else
            {
                if (comp instanceof javax.swing.JPanel)
                {
                    for (Component panComp : panBotonesCliente.getComponents())
                    {
                        if (((javax.swing.JButton)panComp).getText() == "Nuevo" || ((javax.swing.JButton)panComp).getText() == "Salir")
                        {
                            ((javax.swing.JButton)panComp).setEnabled(true);
                        } else
                        {
                            ((javax.swing.JButton)panComp).setEnabled(false);
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_btnGrabarClienteActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNuevoClienteActionPerformed
    {//GEN-HEADEREND:event_btnNuevoClienteActionPerformed
        // Recorrer los componentes de la pestaña y activarlos si son
        // de tipo JTextField
        for (Component comp : tabCliente.getComponents())
        {
            if (comp instanceof javax.swing.JTextField)
            {
                ((javax.swing.JTextField)comp).setEnabled(true);
                ((javax.swing.JTextField)comp).setText("");
            }
        }

        //Pone el foco en el Documento del cliente
        txtDocumento.requestFocus();
        btnNuevoCliente.setEnabled(false);
        btnGrabarCliente.setEnabled(true);
        btnLimpiarTabCliente.setEnabled(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtDireccionActionPerformed
    {//GEN-HEADEREND:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnCalcIntAhorroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCalcIntAhorroActionPerformed
    {//GEN-HEADEREND:event_btnCalcIntAhorroActionPerformed
        // TODO add your handling code here:
        Double inteGenerado;
        
        if(funValidaString(txtNumAhorros.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "El número de la cuenta no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtNumAhorros.requestFocus();
            return;
        }
        
        if(funValidaString(txtSaldoAhorros.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "El saldo de la cuenta no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtSaldoAhorros.requestFocus();
            return;
        }
        
        if(calFechAhorros.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "La fecha de apertura es requerida", "¡Atención!", JOptionPane.ERROR_MESSAGE);
            calFechAhorros.requestFocus();
        }
        
        //
        
        inteGenerado = ((double) spinIntAhorros.getValue()) * ((Number)txtSaldoAhorros.getValue()).doubleValue() / 100;
        txtRendAhorros.setValue(inteGenerado);
        
        
        
          
    }//GEN-LAST:event_btnCalcIntAhorroActionPerformed

    private void btnGrabCtaAhorroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGrabCtaAhorroActionPerformed
    {//GEN-HEADEREND:event_btnGrabCtaAhorroActionPerformed
        // TODO add your handling code here:
        
        CuentaAhorros cuentaAhorros = new CuentaAhorros();
        
        if(funValidaString(txtNumAhorros.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "El número de la cuenta no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtNumAhorros.requestFocus();
            return;
        }
        
        if(funValidaString(txtSaldoAhorros.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "El saldo de la cuenta no puede ser nulo.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtSaldoAhorros.requestFocus();
            return;
        }
        
        if(calFechAhorros.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "La fecha de apertura es requerida", "¡Atención!", JOptionPane.ERROR_MESSAGE);
            calFechAhorros.requestFocus();
            return;
        }
        
        if(spinIntAhorros.getValue() == null) {
            JOptionPane.showMessageDialog(rootPane, "Se requiere el Interés pactado", "¡Atención!", JOptionPane.ERROR_MESSAGE);
            spinIntAhorros.requestFocus();
            return;
        }
      
        
        cuentaAhorros.setNumCuenta(txtNumAhorros.getText());
        cuentaAhorros.setIntCuenta((Double) spinIntAhorros.getValue());
        cuentaAhorros.setSalCuenta(((Number)txtSaldoAhorros.getValue()).doubleValue());
        cuentaAhorros.setFechCuenta(calFechAhorros.getDate());
        
      
        LISTA_AHORROS.add(cuentaAhorros);
        JOptionPane.showMessageDialog(rootPane, "Se grabó la cuenta. Hay " + LISTA_AHORROS.size() + " cuentas registradas.", "Cliente guardado", JOptionPane.INFORMATION_MESSAGE);

        txtNumAhorros.setEnabled(false);
        txtSaldoAhorros.setEnabled(false);
        txtRendAhorros.setEnabled(false);
        spinIntAhorros.setEnabled(false);
        calFechAhorros.setEnabled(false);
        btnNvaCtaAhorro.setEnabled(true);
        btnGrabCtaAhorro.setEnabled(false);
        btnCalcIntAhorro.setEnabled(false);
        btnLimpiarTabAhorro.setEnabled(false);
    }//GEN-LAST:event_btnGrabCtaAhorroActionPerformed

    private void btnLimpiarTabAhorroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLimpiarTabAhorroActionPerformed
    {//GEN-HEADEREND:event_btnLimpiarTabAhorroActionPerformed
        // TODO add your handling code here:
        txtNumAhorros.setText("");
        txtSaldoAhorros.setValue(null);
        txtRendAhorros.setValue(null);
        spinIntAhorros.setValue(1);
        calFechAhorros.setDate(null);
        txtNumAhorros.requestFocus();
    }//GEN-LAST:event_btnLimpiarTabAhorroActionPerformed

    private void btnLimpiarTabCorrienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLimpiarTabCorrienteActionPerformed
    {//GEN-HEADEREND:event_btnLimpiarTabCorrienteActionPerformed
        // TODO add your handling code here:
        txtNumCorriente.setText("");
        txtNumCorriente.requestFocus();
        spinIntCorriente.setValue(1);
        calFechCorriente.setDate(null);
        txtSaldoCorriente.setValue(null);
        txtSobreCorriente.setValue(null);
        txtRendCorriente.setValue(null);
    }//GEN-LAST:event_btnLimpiarTabCorrienteActionPerformed

    private void btnLimpiarTabCDTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLimpiarTabCDTActionPerformed
    {//GEN-HEADEREND:event_btnLimpiarTabCDTActionPerformed
        // TODO add your handling code here:
        txtNumCDT.setText("");
        txtNumCDT.requestFocus();
        calFechCDT.setDate(null);
        spinPlazoCDT.setValue(1);
        spinIntCDT.setValue(1);
        txtMontoCDT.setValue(null);
        txtRendCDT.setValue(null);
        txtRetCDT.setValue(null);
    }//GEN-LAST:event_btnLimpiarTabCDTActionPerformed

    private void btnGrabCDTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGrabCDTActionPerformed
    {//GEN-HEADEREND:event_btnGrabCDTActionPerformed
        // TODO add your handling code here:
        
        CDT Titulo = new CDT();
      
        if(funValidaString(txtNumCDT.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "El número del CDT es requerido","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtNumCDT.requestFocus();
            return;
        }
        
        if(calFechCDT.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "Se requiere la fecha de apertura del CDT","¡Atención!", JOptionPane.ERROR_MESSAGE);
            calFechCDT.requestFocus();
            return;
        }
        
        if(txtMontoCDT.getValue() == null || ((Number)txtMontoCDT.getValue()).intValue() <= 0) {
            JOptionPane.showMessageDialog(rootPane, "El monto del CDT debe ser diferente de cero","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtMontoCDT.requestFocus();
            return;
        }
        
        Titulo.setNumCDT(txtNumCDT.getText());
        Titulo.setFechCDT(calFechCDT.getDate());
        Titulo.setIntCDT(((Number)spinIntCDT.getValue()).doubleValue());
        Titulo.setPlazoCDT(((Number)spinPlazoCDT.getValue()).intValue());
        
        LISTA_CDT.add(Titulo);
        JOptionPane.showMessageDialog(rootPane, "Se grabó el título. Hay " + LISTA_CDT.size() + " títulos registrados.", "Cliente guardado", JOptionPane.INFORMATION_MESSAGE);

        txtNumCDT.setEnabled(false);
        calFechCDT.setEnabled(false);
        spinPlazoCDT.setEnabled(false);
        spinIntCDT.setEnabled(false);
        txtMontoCDT.setEnabled(false);
        txtRendCDT.setEnabled(false);
        txtRetCDT.setEnabled(false);
        
        btnGrabCDT.setEnabled(false);
        btnCalcIntCDT.setEnabled(false);
        btnLimpiarTabCDT.setEnabled(false);
        btnNvoCDT.setEnabled(true);
        
        
    }//GEN-LAST:event_btnGrabCDTActionPerformed

    private void btnGrabCtaCorrienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGrabCtaCorrienteActionPerformed
    {//GEN-HEADEREND:event_btnGrabCtaCorrienteActionPerformed
        // TODO add your handling code here:
        
        CuentaCorriente cuentaCorriente = new CuentaCorriente();
        
        if(funValidaString(txtNumCorriente.getText()) == 1) {
            JOptionPane.showMessageDialog(rootPane, "Se requiere el número de la cuenta","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtNumCorriente.requestFocus();
            return;
        }
        
       if(txtSaldoCorriente.getValue() == null) {
            JOptionPane.showMessageDialog(rootPane, "El saldo de la cuenta es requerido.","¡Atención!", JOptionPane.ERROR_MESSAGE);
            txtSaldoCorriente.requestFocus();
            return;
        }
       
        if(calFechCorriente.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "La fecha de apertura es requerida", "¡Atención!", JOptionPane.ERROR_MESSAGE);
            calFechCorriente.requestFocus();
        }
        
        if(txtSobreCorriente.getValue() == null) {
            txtSobreCorriente.setValue(0);
        }
        
        cuentaCorriente.setNumCuenta(txtNumCorriente.getText());
        cuentaCorriente.setFechCuenta(calFechCorriente.getDate());
        cuentaCorriente.setSalCuenta(((Number)txtSaldoCorriente.getValue()).doubleValue());
        cuentaCorriente.setIntCuenta(((Number)spinIntCorriente.getValue()).doubleValue());
        
        LISTA_CORRIENTE.add(cuentaCorriente);
        JOptionPane.showMessageDialog(rootPane, "Se grabó la cuenta corriente. Hay " + LISTA_CORRIENTE.size() + " cuentas registradas.", "Cliente guardado", JOptionPane.INFORMATION_MESSAGE);
        
        txtNumCorriente.setEnabled(false);
        txtNumCorriente.requestFocus();
        calFechCorriente.setEnabled(false);
        txtSaldoCorriente.setEnabled(false);
        txtSobreCorriente.setEnabled(false);
        txtRendCorriente.setEnabled(false);
        spinIntCorriente.setEnabled(false);
        
        btnNvaCtaCorriente.setEnabled(true);
        btnCalcIntCorriente.setEnabled(false);
        btnGrabCtaCorriente.setEnabled(false);
        btnLimpiarTabCorriente.setEnabled(false);
      
    }//GEN-LAST:event_btnGrabCtaCorrienteActionPerformed

    
    
    private int funValidaString(String aux) {
        
        if (aux.length() > 0) {
            return 0;
        } else {
            return 1;
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcIntAhorro;
    private javax.swing.JButton btnCalcIntCDT;
    private javax.swing.JButton btnCalcIntCorriente;
    private javax.swing.JButton btnCalcTarj;
    private javax.swing.JButton btnGrabCDT;
    private javax.swing.JButton btnGrabCtaAhorro;
    private javax.swing.JButton btnGrabCtaCorriente;
    private javax.swing.JButton btnGrabTarj;
    private javax.swing.JButton btnGrabarCliente;
    private javax.swing.JButton btnLimpiarTabAhorro;
    private javax.swing.JButton btnLimpiarTabCDT;
    private javax.swing.JButton btnLimpiarTabCliente;
    private javax.swing.JButton btnLimpiarTabCorriente;
    private javax.swing.JButton btnLimpiarTabTarj;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNvaCtaAhorro;
    private javax.swing.JButton btnNvaCtaCorriente;
    private javax.swing.JButton btnNvaTarj;
    private javax.swing.JButton btnNvoCDT;
    private javax.swing.JButton btnSalirTabAhorro;
    private javax.swing.JButton btnSalirTabCDT;
    private javax.swing.JButton btnSalirTabCliente;
    private javax.swing.JButton btnSalirTabCorriente;
    private javax.swing.JButton btnSalirTabTarj;
    private com.toedter.calendar.JDateChooser calFechAhorros;
    private com.toedter.calendar.JDateChooser calFechCDT;
    private com.toedter.calendar.JDateChooser calFechCorriente;
    private com.toedter.calendar.JDateChooser calFechExp;
    private com.toedter.calendar.JDateChooser calFechVenc;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCupoAsignado;
    private javax.swing.JLabel lblCupoUsado;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblFechAhorros;
    private javax.swing.JLabel lblFechCDT;
    private javax.swing.JLabel lblFechExp;
    private javax.swing.JLabel lblFechVenc;
    private javax.swing.JLabel lblIngGenAhorro;
    private javax.swing.JLabel lblIntAhorros;
    private javax.swing.JLabel lblIntCDT;
    private javax.swing.JLabel lblIntCorriente;
    private javax.swing.JLabel lblIntGenCDT;
    private javax.swing.JLabel lblIntGenerado;
    private javax.swing.JLabel lblIntTarj;
    private javax.swing.JLabel lblMontoCDT;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumAhorros;
    private javax.swing.JLabel lblNumCDT;
    private javax.swing.JLabel lblNumCorriente;
    private javax.swing.JLabel lblNumTarj;
    private javax.swing.JLabel lblPlazoCDT;
    private javax.swing.JLabel lblRendCorriente;
    private javax.swing.JLabel lblRetCDT;
    private javax.swing.JLabel lblSaldoAhorros;
    private javax.swing.JLabel lblSaldoCorriente;
    private javax.swing.JLabel lblSobreCorriente;
    private javax.swing.JPanel panBotonesAhorro;
    private javax.swing.JPanel panBotonesCDT;
    private javax.swing.JPanel panBotonesCliente;
    private javax.swing.JPanel panBotonesCorriente;
    private javax.swing.JPanel panBotonesTarj;
    private javax.swing.JSpinner spinIntAhorros;
    private javax.swing.JSpinner spinIntCDT;
    private javax.swing.JSpinner spinIntCorriente;
    private javax.swing.JSpinner spinIntPactado;
    private javax.swing.JSpinner spinPlazoCDT;
    private javax.swing.JPanel tabCDAT;
    private javax.swing.JPanel tabCliente;
    private javax.swing.JPanel tabCtaAhorros;
    private javax.swing.JPanel tabCtaCorriente;
    private javax.swing.JTabbedPane tabGroup;
    private javax.swing.JPanel tabTCredito;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JFormattedTextField txtCupoTarj;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JFormattedTextField txtIntGenerado;
    private javax.swing.JFormattedTextField txtMontoCDT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumAhorros;
    private javax.swing.JTextField txtNumCDT;
    private javax.swing.JTextField txtNumCorriente;
    private javax.swing.JTextField txtNumTarj;
    private javax.swing.JFormattedTextField txtRendAhorros;
    private javax.swing.JFormattedTextField txtRendCDT;
    private javax.swing.JFormattedTextField txtRendCorriente;
    private javax.swing.JFormattedTextField txtRetCDT;
    private javax.swing.JFormattedTextField txtSaldoAhorros;
    private javax.swing.JFormattedTextField txtSaldoCorriente;
    private javax.swing.JFormattedTextField txtSobreCorriente;
    private javax.swing.JFormattedTextField txtUsadoTarj;
    // End of variables declaration//GEN-END:variables
}
